[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
guessify_on_solana = "E8izq3XUK9HGB4NQkz8n6mDvQTBoNTW3yg8Ft1XwxBuV"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/dmrdvn/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
